version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/cadastroSimples
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  rabbitmq:
    build:
      context: ./docker/config/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    build:
      context: ./docker/config/mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
